# Generated by Django 5.2.12 on 2026-03-08 02:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=500)),
                ('detailed_description', models.TextField()),
                ('price_inr', models.PositiveIntegerField(help_text='Price in INR (99-799)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='addons/')),
                ('is_active', models.BooleanField(default=True)),
                ('gender_required', models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('any', 'Any')], default='any', max_length=10)),
                ('min_activity_score', models.PositiveIntegerField(default=0, help_text='Minimum activity score (0-100)')),
                ('required_conditions', models.JSONField(blank=True, default=list, help_text="List of conditions required (e.g. ['pcos', 'thyroid'])")),
            ],
            options={
                'verbose_name': 'Premium Add-On',
                'verbose_name_plural': 'Premium Add-Ons',
                'ordering': ['price_inr'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(default='english', max_length=20)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='moderate', max_length=20)),
                ('work_schedule', models.CharField(blank=True, max_length=50)),
                ('sleep_hours', models.FloatField(default=7.0)),
                ('wake_up_time', models.CharField(blank=True, max_length=20)),
                ('tired_time', models.CharField(blank=True, max_length=20)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], default='moderate', max_length=20)),
                ('energy_levels', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('mood_patterns', models.CharField(blank=True, max_length=200)),
                ('exercise_preference', models.CharField(blank=True, max_length=200)),
                ('weight_goal', models.CharField(choices=[('lose', 'Lose Weight'), ('gain', 'Gain Weight'), ('maintain', 'Maintain'), ('build_muscle', 'Build Muscle')], default='maintain', max_length=30)),
                ('meals_per_day', models.PositiveIntegerField(default=3)),
                ('eating_out', models.CharField(blank=True, max_length=50)),
                ('cravings', models.CharField(blank=True, max_length=200)),
                ('hunger_frequency', models.CharField(blank=True, max_length=50)),
                ('hydration_habits', models.CharField(blank=True, max_length=200)),
                ('food_intolerances', models.JSONField(blank=True, default=list)),
                ('supplement_usage', models.TextField(blank=True)),
                ('digestive_issues', models.CharField(blank=True, max_length=200)),
                ('skin_concerns', models.CharField(blank=True, max_length=200)),
                ('medical_conditions', models.JSONField(blank=True, default=list)),
                ('bleeding_frequency', models.CharField(blank=True, max_length=50)),
                ('dna_upload', models.FileField(blank=True, null=True, upload_to='dna/')),
                ('plan_type', models.CharField(choices=[('free', 'Free Starter'), ('essential', 'Essential'), ('premium', 'Premium'), ('coaching', 'Coaching Edition')], default='free', max_length=20)),
                ('purchased_addons', models.JSONField(blank=True, default=list, help_text='List of purchased add-on slugs')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
